# Where should jekyll serve the site locally?
port:        4000
# Where should jekyll put the site?
baseurl:     /
# How should jekyll create permalinks?
permalink:   /blog/:title
# Where should find the site source?
source:      .
# Where should jekyll put the site?
destination: ./_site
# Where jekyll looks for plugins.
plugins_dir:     ./_plugins
# Where jekyll looks for page layouts.
layouts:     ./_layouts
# Don't run in safe mode.
safe:        false
# Don't publish posts with a future date.
future:      false
# Don't create a related posts index.
lsi:         false
# Use kramdown (what a surprise.).
markdown:    kramdown
