# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"

# Gems dependencies to be installed
gem "webrick", "~> 1.7"
# HACK to keep sass-embedded working
gem "jekyll", "~> 4.2.2", group: :jekyll_plugins

# Github Pages plugins
group :jekyll_plugins do
  gem "jekyll-scholar", "~> 7.0"
end

